---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfaas-python3-deployment
  labels:
    app: dfaas-python3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dfaas-python3
  template:
    metadata:
      labels:
        app: dfaas-python3
    spec:
      containers:
      - name: dfaas-python3-deployment
        image: danroblewis/dfaas-container-python3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: dfaas-python3-deployment
spec:
  selector:
    # Selector for Pods
    app: dfaas-python3
  ports:
  # Port Map
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer

